[package]
name = "advent-2022"
version = "0.1.0"
authors = ["apinx <me@apinx.dk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
rand = "0.8.5"
itertools = "0.8.2"